runtime: custom
manual_scaling:
  instances: 1
network:
  forwarded_ports:
    - 80:8080
    - 8082:8082
    - 8083:8083
env_variables:
  GIN_MODE: release
  PORT: :8080
  PARTNER_PORT: :8082
  GAME_PORT: :8083
env: 
  flex