runtime: custom
# manual_scaling:
#   instances: 1
# network:
#   forwarded_ports:
#     - 8081
#     - 8082
#     - 8083
# env_variables:
#   GIN_MODE: release
#   HTTP_PORT: :8081
#   PARTNER_PORT: :8082
#   GAME_PORT: :8083
env: 
  flex